"""Initial migration

Revision ID: 462e885e00d1
Revises: 
Create Date: 2023-05-29 05:02:25.485425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '462e885e00d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lgas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('lga')
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.drop_column('No_of_LGAs')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('No_of_LGAs', sa.VARCHAR(length=100), nullable=True))

    op.create_table('lga',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=45), nullable=False),
    sa.Column('region_id', sa.INTEGER(), nullable=False),
    sa.Column('state_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('lgas')
    # ### end Alembic commands ###
